name: Nightly Build

on:
  # Triggers the workflow at 00:00 UTC every day.
  schedule:
    - cron: '0 0 * * *'
  
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    name: Create Nightly Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code.
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Step 2: Install Specific ARM GCC Toolchain (10.3-2021.10)
      - name: Install ARM GCC Toolchain
        run: |
          echo "Downloading ARM GCC Toolchain..."
          curl -LO https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          echo "Extracting toolchain..."
          tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          TOOLCHAIN_PATH="$GITHUB_WORKSPACE/gcc-arm-none-eabi-10.3-2021.10/bin"
          echo "Adding $TOOLCHAIN_PATH to the system PATH for subsequent steps..."
          echo "$TOOLCHAIN_PATH" >> $GITHUB_PATH

      # Step 3: Verify Toolchain and Download Playdate SDK
      - name: Verify Toolchain and Download SDK
        run: |
          echo "Verifying compiler version:"
          arm-none-eabi-gcc --version
          echo "Downloading and extracting Playdate SDK..."
          curl -LO https://download.panic.com/playdate_sdk/Linux/PlaydateSDK-latest.tar.gz
          tar -xzf PlaydateSDK-latest.tar.gz
          SDK_DIR_NAME=$(ls -d PlaydateSDK-*/ | sed 's,/$,,')
          echo "PLAYDATE_SDK_PATH=$GITHUB_WORKSPACE/$SDK_DIR_NAME" >> $GITHUB_ENV

      # Step 4: Update Build Number in pdxinfo (NEW)
      # This step modifies the buildNumber just for this run.
      - name: Update Build Number
        run: |
          # Get the current date in YYYYMMDD format.
          DATE_STAMP=$(date +'%Y%m%d')
          echo "Updating buildNumber in Source/pdxinfo to $DATE_STAMP"
          
          # Use sed to find the line starting with "buildNumber=" and replace it.
          # The -i flag modifies the file in-place.
          sed -i "s/^buildNumber=.*/buildNumber=$DATE_STAMP/" Source/pdxinfo
          
          echo "Contents of pdxinfo after update:"
          cat Source/pdxinfo

      # Step 5: Build the Project
      # The 'make' command will now use the pdxinfo file with the updated build number.
      - name: Build Project
        run: make device

      # Step 6: Package and Name the Artifact
      - name: Package Artifact
        id: package
        run: |
          APP_VERSION=$(grep '^version=' Source/pdxinfo | cut -d '=' -f 2)
          echo "Extracted App Version: $APP_VERSION"
          DATE_STAMP_HYPHENATED=$(date +'%Y-%m-%d')
          ZIP_FILENAME="CrankBoy-${APP_VERSION}-nightly-${DATE_STAMP_HYPHENATED}.zip"
          echo "Packaging artifact as: $ZIP_FILENAME"
          zip -r "$ZIP_FILENAME" CrankBoy.pdx
          echo "zip_path=$ZIP_FILENAME" >> $GITHUB_OUTPUT

      # Step 7: Upload the Zipped Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.zip_path }}
          path: ${{ steps.package.outputs.zip_path }}
